node version update to v16

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -5,29 +5,28 @@ name: Node.js CI
 
 on:
   push:
-    branches: [ master ]
+    branches: [master]
   pull_request:
-    branches: [ master ]
+    branches: [master]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     strategy:
       matrix:
-        node-version: [10.x, 12.x, 14.x]
+        node-version: [16.x]
 
     steps:
-    - uses: actions/checkout@v2
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v1
-      with:
-        node-version: ${{ matrix.node-version }}
-    - run: npm ci
-    - run: npm run build --if-present
-    # - run: npm test
-    - name: run Lighthouse CI
-      run: |
-        npm install -g @lhci/cli@0.5.x
-        lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=./packages/frontend/dist || echo "LHCI failed!"
+      - uses: actions/checkout@v2
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v1
+        with:
+          node-version: ${{ matrix.node-version }}
+      - run: npm ci
+      - run: npm run build --if-present
+      # - run: npm test
+      - name: run Lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.5.x
+          lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=./packages/frontend/dist || echo "LHCI failed!"
